spring:
  application:
    name: salary-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Salary Service


server:
  port: 9788
logging:
  level:
    root:
    com.hrglobal: DEBUG
---
spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: personal_salary
  datasource:
    url: "jdbc:postgresql://localhost:5432/hr"
    username: postgres
    password: 367300

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

---
spring:
  profiles: stage
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: personal_salary
  datasource:
    url: "jdbc:postgresql://localhost:5432/hr"
    username: postgres
    password: 367300

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}
